# Generated by Django 6.0.4 on 2026-04-21 02:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('region_label', models.CharField(default='China', max_length=120)),
                ('domain_codes', models.JSONField(blank=True, default=list)),
                ('default_parameters', models.JSONField(blank=True, default=dict)),
                ('steps', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '流程模板',
                'verbose_name_plural': '流程模板',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='WorkflowSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('timezone', models.CharField(default='Asia/Shanghai', max_length=64)),
                ('minute', models.CharField(default='0', max_length=20)),
                ('hour', models.CharField(default='2', max_length=20)),
                ('day_of_week', models.CharField(default='*', max_length=20)),
                ('day_of_month', models.CharField(default='*', max_length=20)),
                ('month_of_year', models.CharField(default='*', max_length=20)),
                ('schedule_parameters', models.JSONField(blank=True, default=dict)),
                ('enabled', models.BooleanField(default=True)),
                ('beat_task_name', models.CharField(blank=True, max_length=150)),
                ('last_enqueued_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='workflows.workflowtemplate')),
            ],
            options={
                'verbose_name': '定时任务',
                'verbose_name_plural': '定时任务',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='WorkflowRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trigger_mode', models.CharField(choices=[('manual', 'Manual'), ('schedule', 'Schedule'), ('resume', 'Resume')], default='manual', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('queued', 'Queued'), ('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('partial', 'Partial'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('business_time', models.DateTimeField()),
                ('context', models.JSONField(blank=True, default=dict)),
                ('summary', models.CharField(blank=True, max_length=255)),
                ('run_directory', models.CharField(blank=True, max_length=255)),
                ('log_directory', models.CharField(blank=True, max_length=255)),
                ('output_directory', models.CharField(blank=True, max_length=255)),
                ('is_published', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('failure_summary', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='workflows.workflowtemplate')),
            ],
            options={
                'verbose_name': '流程运行',
                'verbose_name_plural': '流程运行',
                'ordering': ('-business_time', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='WorkflowTaskRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_name', models.CharField(max_length=64)),
                ('display_name', models.CharField(max_length=120)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('ready', 'Ready'), ('submitted', 'Submitted'), ('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='pending', max_length=20)),
                ('step_order', models.PositiveIntegerField(default=0)),
                ('dependencies', models.JSONField(blank=True, default=list)),
                ('slurm_job_id', models.CharField(blank=True, max_length=40)),
                ('command_text', models.TextField(blank=True)),
                ('working_directory', models.CharField(blank=True, max_length=255)),
                ('script_path', models.CharField(blank=True, max_length=255)),
                ('output_log_path', models.CharField(blank=True, max_length=255)),
                ('error_log_path', models.CharField(blank=True, max_length=255)),
                ('expected_outputs', models.JSONField(blank=True, default=list)),
                ('success_marker_path', models.CharField(blank=True, max_length=255)),
                ('retries', models.PositiveIntegerField(default=0)),
                ('max_retries', models.PositiveIntegerField(default=1)),
                ('state_detail', models.JSONField(blank=True, default=dict)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_runs', to='workflows.workflowrun')),
            ],
            options={
                'verbose_name': '任务步骤',
                'verbose_name_plural': '任务步骤',
                'ordering': ('step_order', 'id'),
                'unique_together': {('run', 'step_name')},
            },
        ),
    ]
