/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'inverse-surface': '#e3e2e2',
        'primary-container': '#0066ff',
        'tertiary-container': '#00842c',
        'on-primary-container': '#f8f7ff',
        'surface-tint': '#b3c5ff',
        'on-secondary-fixed': '#002022',
        'error': '#ffb4ab',
        'on-primary-fixed-variant': '#003fa4',
        'outline': '#8c90a1',
        'on-primary': '#002b75',
        'error-container': '#93000a',
        'on-tertiary-fixed': '#002106',
        'inverse-primary': '#0054d6',
        'surface-container-high': '#292a2a',
        'surface-dim': '#121414',
        'on-secondary-container': '#006a70',
        'on-primary-fixed': '#001849',
        'tertiary': '#50e167',
        'background': '#121414',
        'surface-bright': '#383939',
        'on-secondary-fixed-variant': '#004f54',
        'secondary-fixed': '#74f5ff',
        'surface': '#121414',
        'on-error-container': '#ffdad6',
        'surface-container': '#1f2020',
        'surface-container-low': '#1b1c1c',
        'on-surface-variant': '#c2c6d8',
        'inverse-on-surface': '#2f3031',
        'surface-variant': '#343535',
        'primary-fixed-dim': '#b3c5ff',
        'secondary': '#ddfcff',
        'surface-container-highest': '#343535',
        'primary-fixed': '#dae1ff',
        'tertiary-fixed': '#6fff80',
        'outline-variant': '#424656',
        'on-surface': '#e3e2e2',
        'on-tertiary-container': '#e5ffdf',
        'on-tertiary': '#00390e',
        'on-secondary': '#00363a',
        'secondary-fixed-dim': '#00dbe7',
        'tertiary-fixed-dim': '#50e167',
        'on-background': '#e3e2e2',
        'primary': '#b3c5ff',
        'surface-container-lowest': '#0d0e0f',
        'secondary-container': '#00f1fe',
        'on-tertiary-fixed-variant': '#005319',
        'on-error': '#690005',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      spacing: {
        lg: '24px',
        xl: '32px',
        md: '16px',
        xs: '4px',
        gutter: '16px',
        margin: '24px',
        sm: '8px',
        unit: '4px',
      },
      fontFamily: {
        'headline-xl': ['Inter', 'sans-serif'],
        'headline-md': ['Inter', 'sans-serif'],
        'data-mono': ['Space Grotesk', 'monospace'],
        'label-caps': ['Space Grotesk', 'monospace'],
        'body-md': ['Inter', 'sans-serif'],
        'body-lg': ['Inter', 'sans-serif'],
      },
      fontSize: {
        'headline-xl': ['40px', { lineHeight: '48px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-md': ['24px', { lineHeight: '32px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'data-mono': ['14px', { lineHeight: '20px', letterSpacing: '0.02em', fontWeight: '500' }],
        'label-caps': ['12px', { lineHeight: '16px', letterSpacing: '0.1em', fontWeight: '600' }],
        'body-md': ['14px', { lineHeight: '20px', letterSpacing: '0', fontWeight: '400' }],
        'body-lg': ['16px', { lineHeight: '24px', letterSpacing: '0', fontWeight: '400' }],
      },
    },
  },
  plugins: [],
}
