const token = (name) => `rgb(var(--color-${name}) / <alpha-value>)`;

/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'inverse-surface': token('inverse-surface'),
        'primary-container': token('primary-container'),
        'tertiary-container': token('tertiary-container'),
        'on-primary-container': token('on-primary-container'),
        'surface-tint': token('surface-tint'),
        'on-secondary-fixed': token('on-secondary-fixed'),
        'error': token('error'),
        'on-primary-fixed-variant': token('on-primary-fixed-variant'),
        'outline': token('outline'),
        'on-primary': token('on-primary'),
        'error-container': token('error-container'),
        'on-tertiary-fixed': token('on-tertiary-fixed'),
        'inverse-primary': token('inverse-primary'),
        'surface-container-high': token('surface-container-high'),
        'surface-dim': token('surface-dim'),
        'on-secondary-container': token('on-secondary-container'),
        'on-primary-fixed': token('on-primary-fixed'),
        'tertiary': token('tertiary'),
        'background': token('background'),
        'surface-bright': token('surface-bright'),
        'on-secondary-fixed-variant': token('on-secondary-fixed-variant'),
        'secondary-fixed': token('secondary-fixed'),
        'surface': token('surface'),
        'on-error-container': token('on-error-container'),
        'surface-container': token('surface-container'),
        'surface-container-low': token('surface-container-low'),
        'on-surface-variant': token('on-surface-variant'),
        'inverse-on-surface': token('inverse-on-surface'),
        'surface-variant': token('surface-variant'),
        'primary-fixed-dim': token('primary-fixed-dim'),
        'secondary': token('secondary'),
        'surface-container-highest': token('surface-container-highest'),
        'primary-fixed': token('primary-fixed'),
        'tertiary-fixed': token('tertiary-fixed'),
        'outline-variant': token('outline-variant'),
        'on-surface': token('on-surface'),
        'on-tertiary-container': token('on-tertiary-container'),
        'on-tertiary': token('on-tertiary'),
        'on-secondary': token('on-secondary'),
        'secondary-fixed-dim': token('secondary-fixed-dim'),
        'tertiary-fixed-dim': token('tertiary-fixed-dim'),
        'on-background': token('on-background'),
        'primary': token('primary'),
        'surface-container-lowest': token('surface-container-lowest'),
        'secondary-container': token('secondary-container'),
        'on-tertiary-fixed-variant': token('on-tertiary-fixed-variant'),
        'on-error': token('on-error'),
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      spacing: {
        lg: '24px',
        xl: '32px',
        md: '16px',
        xs: '4px',
        gutter: '16px',
        margin: '24px',
        sm: '8px',
        unit: '4px',
      },
      fontFamily: {
        'headline-xl': ['Inter', 'sans-serif'],
        'headline-md': ['Inter', 'sans-serif'],
        'data-mono': ['Space Grotesk', 'monospace'],
        'label-caps': ['Space Grotesk', 'monospace'],
        'body-md': ['Inter', 'sans-serif'],
        'body-lg': ['Inter', 'sans-serif'],
      },
      fontSize: {
        'headline-xl': ['40px', { lineHeight: '48px', letterSpacing: '0', fontWeight: '700' }],
        'headline-md': ['24px', { lineHeight: '32px', letterSpacing: '0', fontWeight: '600' }],
        'data-mono': ['14px', { lineHeight: '20px', letterSpacing: '0.02em', fontWeight: '500' }],
        'label-caps': ['12px', { lineHeight: '16px', letterSpacing: '0.1em', fontWeight: '600' }],
        'body-md': ['14px', { lineHeight: '20px', letterSpacing: '0', fontWeight: '400' }],
        'body-lg': ['16px', { lineHeight: '24px', letterSpacing: '0', fontWeight: '400' }],
      },
    },
  },
  plugins: [],
}
