import paramiko
client = paramiko.SSHClient()
client.set_missing_host_key_policy(paramiko.AutoAddPolicy())
client.connect(hostname='10.40.140.17', port=22, username='anxq', password='ams@2605', timeout=30)
sftp = client.open_sftp()
with sftp.open('/tmp/nml_check.sh', 'w') as f:
    f.write('#!/bin/bash\n')
    f.write('source /etc/profile.d/*.sh 2>/dev/null\n')
    f.write('source ~/.bashrc 2>/dev/null\n')
    f.write('NML=/g7/anxq/Zhangjt/workspace/Smanager/auto-pollen-flow/runs/lijt_hybrid_neimeng_20240701_20240721/case/WRFChem_autumn_Beijing_pre3/WRF-pollen1/WRF-pollen_Tot_Arte_Chen/test/em_real/namelist.input\n')
    f.write('echo "=== NML DOMAINS ==="\n')
    f.write('grep -n -E "num_metgrid|e_we|e_sn|e_vert|num_soil|p_top" "$NML" 2>/dev/null\n')
    f.write('echo "=== NML DATES ==="\n')
    f.write('grep -n -E "start_date|end_date|start_year|end_year|start_month|end_month|start_day|end_day" "$NML" 2>/dev/null\n')
    f.write('echo "=== CASE NML ==="\n')
    f.write('grep -n -E "num_metgrid|e_we|e_sn" /g7/anxq/Zhangjt/workspace/Smanager/auto-pollen-flow/runs/lijt_hybrid_neimeng_20240701_20240721/case/WRFChem_autumn_Beijing_pre3/WRF-pollen1/WRF-pollen_Tot_Arte_Chen/test/em_real/namelist.input 2>/dev/null\n')
sftp.close()
stdin, stdout, stderr = client.exec_command('bash -l /tmp/nml_check.sh', timeout=20)
print(stdout.read().decode())
err = stderr.read().decode()
if err: print('STDERR:', err[:500])
client.close()
