# Generated by Django 6.0.4 on 2026-04-21 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FriendlyLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('url', models.URLField()),
                ('description', models.CharField(blank=True, max_length=255)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('enabled', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': '友情链接',
                'verbose_name_plural': '友情链接',
                'ordering': ('sort_order', 'name'),
            },
        ),
        migrations.CreateModel(
            name='SiteConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='中国花粉传播预报系统', max_length=128)),
                ('subtitle', models.CharField(default='基于 WRF-Chem / WRF-Pollen 的全域花粉传播预报与自动化业务运行平台', max_length=255)),
                ('hero_notice', models.CharField(blank=True, max_length=255)),
                ('copyright_notice', models.CharField(default='Copyright 2026 Pollen Forecast Center', max_length=255)),
                ('map_center_lon', models.FloatField(default=104.0)),
                ('map_center_lat', models.FloatField(default=35.5)),
                ('map_zoom', models.FloatField(default=4.5)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '站点配置',
                'verbose_name_plural': '站点配置',
            },
        ),
    ]
