# Generated by Django 6.0.4 on 2026-04-21 02:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workflows', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForecastDomain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('extent', models.JSONField(default=list, help_text='[min_lon, min_lat, max_lon, max_lat]')),
                ('resolution_km', models.DecimalField(decimal_places=2, default=9.0, max_digits=6)),
                ('center_lon', models.FloatField(default=104.0)),
                ('center_lat', models.FloatField(default=35.5)),
                ('default_opacity', models.FloatField(default=0.72)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': '预报域',
                'verbose_name_plural': '预报域',
                'ordering': ('sort_order', 'code'),
            },
        ),
        migrations.CreateModel(
            name='PollenType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=100)),
                ('scientific_name', models.CharField(blank=True, max_length=150)),
                ('description', models.TextField(blank=True)),
                ('color_hex', models.CharField(default='#69c0ff', max_length=7)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': '花粉类别',
                'verbose_name_plural': '花粉类别',
                'ordering': ('sort_order', 'name'),
            },
        ),
        migrations.CreateModel(
            name='PointQueryProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
                ('chart_type', models.CharField(choices=[('line', '折线图'), ('bar', '柱状图')], default='line', max_length=20)),
                ('sample_series', models.JSONField(blank=True, default=list)),
                ('is_featured', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('domain', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='point_profiles', to='forecast.forecastdomain')),
                ('pollen_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='point_profiles', to='forecast.pollentype')),
            ],
            options={
                'verbose_name': '点位分析配置',
                'verbose_name_plural': '点位分析配置',
                'ordering': ('sort_order', 'name'),
            },
        ),
        migrations.CreateModel(
            name='ForecastProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_time', models.DateTimeField()),
                ('valid_time', models.DateTimeField()),
                ('forecast_hour', models.PositiveIntegerField(default=0)),
                ('geotiff_path', models.CharField(blank=True, max_length=255)),
                ('tile_url_template', models.CharField(blank=True, max_length=255)),
                ('preview_image_path', models.CharField(blank=True, max_length=255)),
                ('stats_json_path', models.CharField(blank=True, max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('passed_validation', models.BooleanField(default=False)),
                ('is_published', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='forecast.forecastdomain')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='workflows.workflowrun')),
                ('pollen_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='forecast.pollentype')),
            ],
            options={
                'verbose_name': '预报产物',
                'verbose_name_plural': '预报产物',
                'ordering': ('-valid_time', 'domain__code', 'pollen_type__name'),
                'unique_together': {('run', 'pollen_type', 'domain', 'valid_time')},
            },
        ),
    ]
